// Copyright 2025-present the zvec project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Golden-byte and robustness tests for ManifestCodec.
//!
//! The byte arrays below pin the on-disk manifest format: decoding them must
//! yield the expected values and re-encoding must reproduce the exact same
//! bytes. All of them were produced by protobuf implementations:
//!
//! - kGoldenEmpty, kGoldenSimple and kGoldenAllIndexTypes were generated by
//!   the libprotobuf-based serializer zvec used before ManifestCodec existed.
//! - Every array in this file has additionally been reproduced byte-for-byte
//!   by an independent protobuf implementation compiled from the archived
//!   proto definition (src/db/proto/zvec.proto as it existed before it was
//!   removed), so none of the bytes are trusted blindly.
//!
//! These tests do not depend on libprotobuf, so they keep guarding format
//! compatibility after that dependency is dropped.
//!
//! Never regenerate these arrays to make a failing test pass: a mismatch means
//! the persisted format changed and existing collections would fail to open.

#include <cstdint>
#include <limits>
#include <memory>
#include <string>
#include <vector>
#include <gtest/gtest.h>
#include "db/index/common/manifest/pb_wire.h"
#include "db/index/common/manifest_codec.h"

using namespace zvec;

namespace {

//! Manifest of a default-constructed schema with no fields. Note that this is
//! not a truly empty manifest: the schema message is present and carries the
//! C++ default max_doc_count_per_segment. Zero-byte input is covered by
//! ZeroByteInput below.
const uint8_t kGoldenEmpty[] = {
    0x12, 0x05, 0x18, 0x80, 0xad, 0xe2, 0x04,
};

//! Manifest with a scalar field, an HNSW vector field and one segment.
const uint8_t kGoldenSimple[] = {
    0x12, 0x31, 0x0a, 0x06, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x12, 0x06,
    0x0a, 0x02, 0x70, 0x6b, 0x10, 0x02, 0x12, 0x1b, 0x0a, 0x05, 0x64, 0x65,
    0x6e, 0x73, 0x65, 0x10, 0x17, 0x18, 0x80, 0x01, 0x2a, 0x0d, 0x12, 0x0b,
    0x0a, 0x04, 0x08, 0x02, 0x22, 0x00, 0x10, 0x10, 0x18, 0xc8, 0x01, 0x18,
    0xa0, 0x8d, 0x06, 0x18, 0x01, 0x22, 0x0a, 0x12, 0x08, 0x10, 0x01, 0x28,
    0x0a, 0x32, 0x02, 0x70, 0x6b, 0x40, 0x01,
};

//! Manifest exercising every IndexParams oneof branch except IVF_RABITQ (see
//! kGoldenAllNineIndexTypes for the complete set), both segment slots and
//! all scalar manifest fields.
const uint8_t kGoldenAllIndexTypes[] = {
    0x12, 0xc1, 0x02, 0x0a, 0x04, 0x72, 0x69, 0x63, 0x68, 0x12, 0x14, 0x0a,
    0x08, 0x66, 0x5f, 0x69, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x10, 0x05, 0x20,
    0x01, 0x2a, 0x04, 0x0a, 0x02, 0x08, 0x01, 0x12, 0x24, 0x0a, 0x06, 0x66,
    0x5f, 0x68, 0x6e, 0x73, 0x77, 0x10, 0x17, 0x18, 0x80, 0x01, 0x20, 0x01,
    0x2a, 0x13, 0x12, 0x11, 0x0a, 0x08, 0x08, 0x01, 0x10, 0x02, 0x22, 0x02,
    0x08, 0x01, 0x10, 0x10, 0x18, 0xc8, 0x01, 0x20, 0x01, 0x12, 0x1a, 0x0a,
    0x06, 0x66, 0x5f, 0x66, 0x6c, 0x61, 0x74, 0x10, 0x16, 0x18, 0x40, 0x20,
    0x01, 0x2a, 0x0a, 0x1a, 0x08, 0x0a, 0x06, 0x08, 0x02, 0x10, 0x01, 0x22,
    0x00, 0x12, 0x22, 0x0a, 0x05, 0x66, 0x5f, 0x69, 0x76, 0x66, 0x10, 0x1a,
    0x18, 0x20, 0x20, 0x01, 0x2a, 0x13, 0x22, 0x11, 0x0a, 0x08, 0x08, 0x03,
    0x10, 0x03, 0x22, 0x02, 0x08, 0x01, 0x10, 0x80, 0x04, 0x18, 0x0c, 0x20,
    0x01, 0x12, 0x29, 0x0a, 0x08, 0x66, 0x5f, 0x72, 0x61, 0x62, 0x69, 0x74,
    0x71, 0x10, 0x17, 0x18, 0x80, 0x02, 0x20, 0x01, 0x2a, 0x16, 0x2a, 0x14,
    0x0a, 0x04, 0x08, 0x01, 0x10, 0x04, 0x10, 0x18, 0x18, 0x96, 0x01, 0x20,
    0x05, 0x28, 0x80, 0x08, 0x30, 0xd0, 0x86, 0x03, 0x12, 0x2b, 0x0a, 0x08,
    0x66, 0x5f, 0x76, 0x61, 0x6d, 0x61, 0x6c, 0x61, 0x10, 0x17, 0x18, 0x60,
    0x20, 0x01, 0x2a, 0x19, 0x32, 0x17, 0x0a, 0x08, 0x08, 0x01, 0x10, 0x04,
    0x22, 0x02, 0x08, 0x01, 0x10, 0x30, 0x18, 0x60, 0x25, 0xcd, 0xcc, 0xac,
    0x3f, 0x28, 0x01, 0x38, 0x01, 0x12, 0x2b, 0x0a, 0x05, 0x66, 0x5f, 0x66,
    0x74, 0x73, 0x10, 0x02, 0x20, 0x01, 0x2a, 0x1e, 0x3a, 0x1c, 0x0a, 0x05,
    0x6a, 0x69, 0x65, 0x62, 0x61, 0x12, 0x09, 0x6c, 0x6f, 0x77, 0x65, 0x72,
    0x63, 0x61, 0x73, 0x65, 0x12, 0x04, 0x73, 0x74, 0x6f, 0x70, 0x1a, 0x02,
    0x7b, 0x7d, 0x12, 0x25, 0x0a, 0x09, 0x66, 0x5f, 0x64, 0x69, 0x73, 0x6b,
    0x61, 0x6e, 0x6e, 0x10, 0x17, 0x18, 0x80, 0x04, 0x20, 0x01, 0x2a, 0x11,
    0x42, 0x0f, 0x0a, 0x06, 0x08, 0x01, 0x10, 0x02, 0x22, 0x00, 0x10, 0x40,
    0x18, 0x80, 0x01, 0x20, 0x10, 0x12, 0x0d, 0x0a, 0x07, 0x66, 0x5f, 0x70,
    0x6c, 0x61, 0x69, 0x6e, 0x10, 0x30, 0x20, 0x01, 0x18, 0x80, 0x80, 0x40,
    0x18, 0x01, 0x22, 0x16, 0x12, 0x0c, 0x10, 0x01, 0x20, 0xe7, 0x07, 0x28,
    0xe8, 0x07, 0x32, 0x02, 0x70, 0x6b, 0x22, 0x06, 0x66, 0x5f, 0x68, 0x6e,
    0x73, 0x77, 0x22, 0x1d, 0x08, 0x01, 0x12, 0x11, 0x08, 0x01, 0x10, 0x01,
    0x18, 0xe8, 0x07, 0x20, 0xcf, 0x0f, 0x28, 0xe8, 0x07, 0x32, 0x02, 0x70,
    0x6b, 0x22, 0x06, 0x66, 0x5f, 0x68, 0x6e, 0x73, 0x77, 0x2a, 0x06, 0x08,
    0x02, 0x1a, 0x02, 0x10, 0x01, 0x30, 0x05, 0x38, 0x09, 0x40, 0x0c,
};

//! IVF_RABITQ index params.
//!
//! The proto definition already supported IVF_RABITQ while libprotobuf was
//! still in the tree (IndexParams.ivf_rabitq = 9, IvfRabitqIndexParams
//! { base = 1, nlist = 2, total_bits = 3, sample_count = 4 }), but the
//! byte-level cross-check suite of that time covered only the other eight
//! oneof branches, so this array was originally encoded by hand from the wire
//! format. It has since been verified against an independent protobuf
//! implementation compiled from the archived zvec.proto: encoding
//! IvfRabitqIndexParams(L2, nlist 1024, total_bits 5, sample_count 100000)
//! reproduces these bytes exactly.
//!
//! Byte layout:
//!   4a 0f                    ivf_rabitq branch, 15 bytes of payload
//!   0a 04 08 01 10 04        base { metric = MT_L2, quantize = QT_RABITQ }
//!   10 80 08                 nlist = 1024
//!   18 05                    total_bits = 5
//!   20 a0 8d 06              sample_count = 100000
const uint8_t kGoldenIvfRabitq[] = {
    0x4a, 0x0f, 0x0a, 0x04, 0x08, 0x01, 0x10, 0x04, 0x10,
    0x80, 0x08, 0x18, 0x05, 0x20, 0xa0, 0x8d, 0x06,
};

//! Manifest carrying no schema message at all:
//!   enable_mmap = true, id_map_path_suffix = 3, next_segment_id = 7
//! The old protobuf reader decoded such a file into a default (empty) schema
//! with max_doc_count_per_segment zero; ManifestCodec keeps that behaviour.
const uint8_t kGoldenNoSchema[] = {
    0x18, 0x01, 0x30, 0x03, 0x40, 0x07,
};

//! What re-encoding kGoldenNoSchema must produce: the schema fallback is
//! written back as an empty-but-present schema message, matching the old
//! load-then-save behaviour.
const uint8_t kGoldenNoSchemaCanonical[] = {
    0x12, 0x00, 0x18, 0x01, 0x30, 0x03, 0x40, 0x07,
};

//! Manifest holding an empty-but-present schema message.
const uint8_t kGoldenEmptySchemaMsg[] = {
    0x12,
    0x00,
};

//! Schema present but max_doc_count_per_segment absent on the wire; it must
//! decode to zero (the value the protobuf reader produced), not to the C++
//! default.
const uint8_t kGoldenSchemaNoMaxDocCount[] = {
    0x12, 0x07, 0x0a, 0x05, 0x6e, 0x6f, 0x6d, 0x61, 0x78,
};

//! Field whose index_params message is present but carries no oneof branch;
//! it must decode to a null IndexParams and be dropped on re-encoding.
const uint8_t kGoldenEmptyIndexParamsMsg[] = {
    0x0a, 0x01, 0x78, 0x10, 0x02, 0x2a, 0x00,
};

//! Every oneof branch with all-default values. Pins proto3 default omission
//! versus message presence: each branch stays present on the wire as an
//! (almost) empty message, base stays present for every vector index, and
//! quantizer_param stays present for all types except HNSW_RABITQ and
//! IVF_RABITQ.
const uint8_t kGoldenAllDefaultIndexParams[] = {
    0x12, 0xcb, 0x01, 0x0a, 0x08, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
    0x73, 0x12, 0x10, 0x0a, 0x08, 0x64, 0x5f, 0x69, 0x6e, 0x76, 0x65, 0x72,
    0x74, 0x10, 0x05, 0x2a, 0x02, 0x0a, 0x00, 0x12, 0x12, 0x0a, 0x06, 0x64,
    0x5f, 0x68, 0x6e, 0x73, 0x77, 0x10, 0x17, 0x2a, 0x06, 0x12, 0x04, 0x0a,
    0x02, 0x22, 0x00, 0x12, 0x12, 0x0a, 0x06, 0x64, 0x5f, 0x66, 0x6c, 0x61,
    0x74, 0x10, 0x17, 0x2a, 0x06, 0x1a, 0x04, 0x0a, 0x02, 0x22, 0x00, 0x12,
    0x11, 0x0a, 0x05, 0x64, 0x5f, 0x69, 0x76, 0x66, 0x10, 0x17, 0x2a, 0x06,
    0x22, 0x04, 0x0a, 0x02, 0x22, 0x00, 0x12, 0x19, 0x0a, 0x0d, 0x64, 0x5f,
    0x68, 0x6e, 0x73, 0x77, 0x5f, 0x72, 0x61, 0x62, 0x69, 0x74, 0x71, 0x10,
    0x17, 0x2a, 0x06, 0x2a, 0x04, 0x0a, 0x02, 0x10, 0x04, 0x12, 0x14, 0x0a,
    0x08, 0x64, 0x5f, 0x76, 0x61, 0x6d, 0x61, 0x6c, 0x61, 0x10, 0x17, 0x2a,
    0x06, 0x32, 0x04, 0x0a, 0x02, 0x22, 0x00, 0x12, 0x0d, 0x0a, 0x05, 0x64,
    0x5f, 0x66, 0x74, 0x73, 0x10, 0x02, 0x2a, 0x02, 0x3a, 0x00, 0x12, 0x15,
    0x0a, 0x09, 0x64, 0x5f, 0x64, 0x69, 0x73, 0x6b, 0x61, 0x6e, 0x6e, 0x10,
    0x17, 0x2a, 0x06, 0x42, 0x04, 0x0a, 0x02, 0x22, 0x00, 0x12, 0x18, 0x0a,
    0x0c, 0x64, 0x5f, 0x69, 0x76, 0x66, 0x5f, 0x72, 0x61, 0x62, 0x69, 0x74,
    0x71, 0x10, 0x17, 0x2a, 0x06, 0x4a, 0x04, 0x0a, 0x02, 0x10, 0x04, 0x18,
    0x80, 0x20,
};

//! Multiple segments and blocks covering every BlockType, multi-column
//! blocks, a writing block inside a persisted segment and repeated indexed
//! vector fields.
const uint8_t kGoldenMultiBlock[] = {
    0x12, 0x53, 0x0a, 0x05, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x12, 0x06, 0x0a,
    0x02, 0x70, 0x6b, 0x10, 0x02, 0x12, 0x19, 0x0a, 0x05, 0x64, 0x65, 0x6e,
    0x73, 0x65, 0x10, 0x17, 0x18, 0x04, 0x2a, 0x0c, 0x12, 0x0a, 0x0a, 0x04,
    0x08, 0x01, 0x22, 0x00, 0x10, 0x08, 0x18, 0x40, 0x12, 0x24, 0x0a, 0x05,
    0x74, 0x69, 0x74, 0x6c, 0x65, 0x10, 0x02, 0x20, 0x01, 0x2a, 0x17, 0x3a,
    0x15, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x12,
    0x09, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x63, 0x61, 0x73, 0x65, 0x18, 0x88,
    0x27, 0x22, 0x7f, 0x08, 0x03, 0x12, 0x0c, 0x10, 0x01, 0x20, 0xe7, 0x07,
    0x28, 0xe8, 0x07, 0x32, 0x02, 0x70, 0x6b, 0x12, 0x11, 0x08, 0x01, 0x10,
    0x03, 0x20, 0xe7, 0x07, 0x28, 0xe8, 0x07, 0x32, 0x05, 0x64, 0x65, 0x6e,
    0x73, 0x65, 0x12, 0x14, 0x08, 0x02, 0x10, 0x04, 0x18, 0xe8, 0x07, 0x20,
    0xcf, 0x0f, 0x28, 0xe8, 0x07, 0x32, 0x05, 0x64, 0x65, 0x6e, 0x73, 0x65,
    0x12, 0x15, 0x08, 0x03, 0x10, 0x02, 0x20, 0xcf, 0x0f, 0x28, 0xd0, 0x0f,
    0x32, 0x02, 0x70, 0x6b, 0x32, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
    0x11, 0x08, 0x04, 0x10, 0x05, 0x20, 0xcf, 0x0f, 0x28, 0xd0, 0x0f, 0x32,
    0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x1a, 0x0c, 0x08, 0x09, 0x10, 0x01,
    0x18, 0xd0, 0x0f, 0x20, 0xd4, 0x0f, 0x28, 0x05, 0x22, 0x05, 0x64, 0x65,
    0x6e, 0x73, 0x65, 0x22, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x02,
    0x08, 0x04, 0x2a, 0x06, 0x08, 0x05, 0x1a, 0x02, 0x10, 0x01, 0x40, 0x06,
};

//! Boundary values: version, uint32/uint64 maxima, INT32_MAX varints, a
//! negative float alpha and empty repeated strings.
const uint8_t kGoldenBoundary[] = {
    0x08, 0x01, 0x12, 0x7a, 0x0a, 0x08, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x61,
    0x72, 0x79, 0x12, 0x2b, 0x0a, 0x03, 0x76, 0x65, 0x63, 0x10, 0x17, 0x18,
    0xff, 0xff, 0xff, 0xff, 0x0f, 0x20, 0x01, 0x2a, 0x1a, 0x12, 0x18, 0x0a,
    0x08, 0x08, 0x03, 0x10, 0x02, 0x22, 0x02, 0x08, 0x01, 0x10, 0xff, 0xff,
    0xff, 0xff, 0x07, 0x18, 0xff, 0xff, 0xff, 0xff, 0x07, 0x20, 0x01, 0x12,
    0x24, 0x0a, 0x03, 0x76, 0x61, 0x6d, 0x10, 0x17, 0x18, 0x08, 0x2a, 0x19,
    0x32, 0x17, 0x0a, 0x04, 0x08, 0x02, 0x22, 0x00, 0x10, 0xff, 0xff, 0xff,
    0xff, 0x07, 0x18, 0xff, 0xff, 0xff, 0xff, 0x07, 0x25, 0x00, 0x00, 0x20,
    0xc0, 0x12, 0x10, 0x0a, 0x04, 0x66, 0x74, 0x73, 0x32, 0x10, 0x02, 0x2a,
    0x06, 0x3a, 0x04, 0x12, 0x00, 0x12, 0x00, 0x18, 0xff, 0xff, 0xff, 0xff,
    0xff, 0xff, 0xff, 0xff, 0xff, 0x01, 0x18, 0x01, 0x22, 0x30, 0x08, 0x07,
    0x12, 0x27, 0x08, 0xff, 0xff, 0xff, 0xff, 0x0f, 0x10, 0x03, 0x18, 0xfe,
    0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01, 0x20, 0xff, 0xff,
    0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01, 0x28, 0xff, 0xff, 0xff,
    0xff, 0x0f, 0x32, 0x01, 0x78, 0x22, 0x03, 0x76, 0x65, 0x63, 0x30, 0xff,
    0xff, 0xff, 0xff, 0x0f, 0x38, 0xff, 0xff, 0xff, 0xff, 0x0f, 0x40, 0xff,
    0xff, 0xff, 0xff, 0x0f,
};

//! The manifest of kGoldenAllIndexTypes plus an IVF_RABITQ field: all nine
//! oneof branches together in one full manifest.
const uint8_t kGoldenAllNineIndexTypes[] = {
    0x12, 0xec, 0x02, 0x0a, 0x05, 0x72, 0x69, 0x63, 0x68, 0x39, 0x12, 0x14,
    0x0a, 0x08, 0x66, 0x5f, 0x69, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x10, 0x05,
    0x20, 0x01, 0x2a, 0x04, 0x0a, 0x02, 0x08, 0x01, 0x12, 0x24, 0x0a, 0x06,
    0x66, 0x5f, 0x68, 0x6e, 0x73, 0x77, 0x10, 0x17, 0x18, 0x80, 0x01, 0x20,
    0x01, 0x2a, 0x13, 0x12, 0x11, 0x0a, 0x08, 0x08, 0x01, 0x10, 0x02, 0x22,
    0x02, 0x08, 0x01, 0x10, 0x10, 0x18, 0xc8, 0x01, 0x20, 0x01, 0x12, 0x1a,
    0x0a, 0x06, 0x66, 0x5f, 0x66, 0x6c, 0x61, 0x74, 0x10, 0x16, 0x18, 0x40,
    0x20, 0x01, 0x2a, 0x0a, 0x1a, 0x08, 0x0a, 0x06, 0x08, 0x02, 0x10, 0x01,
    0x22, 0x00, 0x12, 0x22, 0x0a, 0x05, 0x66, 0x5f, 0x69, 0x76, 0x66, 0x10,
    0x1a, 0x18, 0x20, 0x20, 0x01, 0x2a, 0x13, 0x22, 0x11, 0x0a, 0x08, 0x08,
    0x03, 0x10, 0x03, 0x22, 0x02, 0x08, 0x01, 0x10, 0x80, 0x04, 0x18, 0x0c,
    0x20, 0x01, 0x12, 0x29, 0x0a, 0x08, 0x66, 0x5f, 0x72, 0x61, 0x62, 0x69,
    0x74, 0x71, 0x10, 0x17, 0x18, 0x80, 0x02, 0x20, 0x01, 0x2a, 0x16, 0x2a,
    0x14, 0x0a, 0x04, 0x08, 0x01, 0x10, 0x04, 0x10, 0x18, 0x18, 0x96, 0x01,
    0x20, 0x05, 0x28, 0x80, 0x08, 0x30, 0xd0, 0x86, 0x03, 0x12, 0x2b, 0x0a,
    0x08, 0x66, 0x5f, 0x76, 0x61, 0x6d, 0x61, 0x6c, 0x61, 0x10, 0x17, 0x18,
    0x60, 0x20, 0x01, 0x2a, 0x19, 0x32, 0x17, 0x0a, 0x08, 0x08, 0x01, 0x10,
    0x04, 0x22, 0x02, 0x08, 0x01, 0x10, 0x30, 0x18, 0x60, 0x25, 0xcd, 0xcc,
    0xac, 0x3f, 0x28, 0x01, 0x38, 0x01, 0x12, 0x2b, 0x0a, 0x05, 0x66, 0x5f,
    0x66, 0x74, 0x73, 0x10, 0x02, 0x20, 0x01, 0x2a, 0x1e, 0x3a, 0x1c, 0x0a,
    0x05, 0x6a, 0x69, 0x65, 0x62, 0x61, 0x12, 0x09, 0x6c, 0x6f, 0x77, 0x65,
    0x72, 0x63, 0x61, 0x73, 0x65, 0x12, 0x04, 0x73, 0x74, 0x6f, 0x70, 0x1a,
    0x02, 0x7b, 0x7d, 0x12, 0x25, 0x0a, 0x09, 0x66, 0x5f, 0x64, 0x69, 0x73,
    0x6b, 0x61, 0x6e, 0x6e, 0x10, 0x17, 0x18, 0x80, 0x04, 0x20, 0x01, 0x2a,
    0x11, 0x42, 0x0f, 0x0a, 0x06, 0x08, 0x01, 0x10, 0x02, 0x22, 0x00, 0x10,
    0x40, 0x18, 0x80, 0x01, 0x20, 0x10, 0x12, 0x28, 0x0a, 0x0c, 0x66, 0x5f,
    0x69, 0x76, 0x66, 0x5f, 0x72, 0x61, 0x62, 0x69, 0x74, 0x71, 0x10, 0x17,
    0x18, 0x80, 0x08, 0x20, 0x01, 0x2a, 0x11, 0x4a, 0x0f, 0x0a, 0x04, 0x08,
    0x01, 0x10, 0x04, 0x10, 0x80, 0x10, 0x18, 0x06, 0x20, 0xc0, 0x9a, 0x0c,
    0x12, 0x0d, 0x0a, 0x07, 0x66, 0x5f, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x10,
    0x30, 0x20, 0x01, 0x18, 0x80, 0x80, 0x40, 0x18, 0x01, 0x22, 0x16, 0x12,
    0x0c, 0x10, 0x01, 0x20, 0xe7, 0x07, 0x28, 0xe8, 0x07, 0x32, 0x02, 0x70,
    0x6b, 0x22, 0x06, 0x66, 0x5f, 0x68, 0x6e, 0x73, 0x77, 0x22, 0x1d, 0x08,
    0x01, 0x12, 0x11, 0x08, 0x01, 0x10, 0x01, 0x18, 0xe8, 0x07, 0x20, 0xcf,
    0x0f, 0x28, 0xe8, 0x07, 0x32, 0x02, 0x70, 0x6b, 0x22, 0x06, 0x66, 0x5f,
    0x68, 0x6e, 0x73, 0x77, 0x2a, 0x06, 0x08, 0x02, 0x1a, 0x02, 0x10, 0x01,
    0x30, 0x05, 0x38, 0x09, 0x40, 0x0c,
};

template <size_t N>
std::string Golden(const uint8_t (&bytes)[N]) {
  return std::string(reinterpret_cast<const char *>(bytes), N);
}

//! Decodes a golden buffer and re-encodes it, expecting identical bytes.
ManifestData ExpectStableRoundTrip(const std::string &golden,
                                   const char *name) {
  ManifestData data;
  EXPECT_TRUE(ManifestCodec::Decode(golden, &data).ok()) << name;

  std::string reencoded;
  EXPECT_TRUE(ManifestCodec::Encode(data, &reencoded).ok()) << name;
  EXPECT_EQ(reencoded, golden)
      << "re-encoding " << name
      << " changed the bytes; the on-disk manifest format must stay stable";
  return data;
}

//! Checks the fields shared by kGoldenAllIndexTypes and
//! kGoldenAllNineIndexTypes. When with_ivf_rabitq is true, an IVF_RABITQ
//! field is expected between f_diskann and f_plain.
void ExpectRichSchemaFields(const CollectionSchema &schema,
                            bool with_ivf_rabitq) {
  const auto fields = schema.fields();
  ASSERT_EQ(fields.size(), with_ivf_rabitq ? 10u : 9u);
  for (const auto &field : fields) {
    EXPECT_TRUE(field->nullable());
  }

  EXPECT_EQ(fields[0]->name(), "f_invert");
  EXPECT_EQ(fields[0]->data_type(), DataType::INT64);
  EXPECT_EQ(fields[0]->dimension(), 0u);
  const auto invert =
      dynamic_cast<const InvertIndexParams *>(fields[0]->index_params().get());
  ASSERT_NE(invert, nullptr);
  EXPECT_EQ(invert->type(), IndexType::INVERT);
  EXPECT_TRUE(invert->enable_range_optimization());

  EXPECT_EQ(fields[1]->name(), "f_hnsw");
  EXPECT_EQ(fields[1]->data_type(), DataType::VECTOR_FP32);
  EXPECT_EQ(fields[1]->dimension(), 128u);
  const auto hnsw =
      dynamic_cast<const HnswIndexParams *>(fields[1]->index_params().get());
  ASSERT_NE(hnsw, nullptr);
  EXPECT_EQ(hnsw->metric_type(), MetricType::L2);
  EXPECT_EQ(hnsw->m(), 16);
  EXPECT_EQ(hnsw->ef_construction(), 200);
  EXPECT_EQ(hnsw->quantize_type(), QuantizeType::INT8);
  EXPECT_TRUE(hnsw->use_contiguous_memory());
  EXPECT_TRUE(hnsw->quantizer_param().enable_rotate());

  EXPECT_EQ(fields[2]->name(), "f_flat");
  EXPECT_EQ(fields[2]->data_type(), DataType::VECTOR_FP16);
  EXPECT_EQ(fields[2]->dimension(), 64u);
  const auto flat =
      dynamic_cast<const FlatIndexParams *>(fields[2]->index_params().get());
  ASSERT_NE(flat, nullptr);
  EXPECT_EQ(flat->metric_type(), MetricType::IP);
  EXPECT_EQ(flat->quantize_type(), QuantizeType::FP16);
  EXPECT_FALSE(flat->quantizer_param().enable_rotate());

  EXPECT_EQ(fields[3]->name(), "f_ivf");
  EXPECT_EQ(fields[3]->data_type(), DataType::VECTOR_INT8);
  EXPECT_EQ(fields[3]->dimension(), 32u);
  const auto ivf =
      dynamic_cast<const IVFIndexParams *>(fields[3]->index_params().get());
  ASSERT_NE(ivf, nullptr);
  EXPECT_EQ(ivf->metric_type(), MetricType::COSINE);
  EXPECT_EQ(ivf->n_list(), 512);
  EXPECT_EQ(ivf->n_iters(), 12);
  EXPECT_TRUE(ivf->use_soar());
  EXPECT_EQ(ivf->quantize_type(), QuantizeType::INT4);
  EXPECT_TRUE(ivf->quantizer_param().enable_rotate());

  EXPECT_EQ(fields[4]->name(), "f_rabitq");
  EXPECT_EQ(fields[4]->data_type(), DataType::VECTOR_FP32);
  EXPECT_EQ(fields[4]->dimension(), 256u);
  const auto hnsw_rabitq = dynamic_cast<const HnswRabitqIndexParams *>(
      fields[4]->index_params().get());
  ASSERT_NE(hnsw_rabitq, nullptr);
  EXPECT_EQ(hnsw_rabitq->metric_type(), MetricType::L2);
  EXPECT_EQ(hnsw_rabitq->quantize_type(), QuantizeType::RABITQ);
  EXPECT_EQ(hnsw_rabitq->m(), 24);
  EXPECT_EQ(hnsw_rabitq->ef_construction(), 150);
  EXPECT_EQ(hnsw_rabitq->total_bits(), 5);
  EXPECT_EQ(hnsw_rabitq->num_clusters(), 1024);
  EXPECT_EQ(hnsw_rabitq->sample_count(), 50000);

  // The original generator misspelled this field name; the bytes are pinned,
  // so the typo is part of the format now.
  EXPECT_EQ(fields[5]->name(), "f_vamala");
  EXPECT_EQ(fields[5]->data_type(), DataType::VECTOR_FP32);
  EXPECT_EQ(fields[5]->dimension(), 96u);
  const auto vamana =
      dynamic_cast<const VamanaIndexParams *>(fields[5]->index_params().get());
  ASSERT_NE(vamana, nullptr);
  EXPECT_EQ(vamana->metric_type(), MetricType::L2);
  EXPECT_EQ(vamana->quantize_type(), QuantizeType::RABITQ);
  EXPECT_TRUE(vamana->quantizer_param().enable_rotate());
  EXPECT_EQ(vamana->max_degree(), 48);
  EXPECT_EQ(vamana->search_list_size(), 96);
  EXPECT_FLOAT_EQ(vamana->alpha(), 1.35f);
  EXPECT_TRUE(vamana->saturate_graph());
  EXPECT_FALSE(vamana->use_contiguous_memory());
  EXPECT_TRUE(vamana->use_id_map());

  EXPECT_EQ(fields[6]->name(), "f_fts");
  EXPECT_EQ(fields[6]->data_type(), DataType::STRING);
  EXPECT_EQ(fields[6]->dimension(), 0u);
  const auto fts =
      dynamic_cast<const FtsIndexParams *>(fields[6]->index_params().get());
  ASSERT_NE(fts, nullptr);
  EXPECT_EQ(fts->tokenizer_name(), "jieba");
  ASSERT_EQ(fts->filters().size(), 2u);
  EXPECT_EQ(fts->filters()[0], "lowercase");
  EXPECT_EQ(fts->filters()[1], "stop");
  EXPECT_EQ(fts->extra_params(), "{}");

  EXPECT_EQ(fields[7]->name(), "f_diskann");
  EXPECT_EQ(fields[7]->data_type(), DataType::VECTOR_FP32);
  EXPECT_EQ(fields[7]->dimension(), 512u);
  const auto diskann =
      dynamic_cast<const DiskAnnIndexParams *>(fields[7]->index_params().get());
  ASSERT_NE(diskann, nullptr);
  EXPECT_EQ(diskann->metric_type(), MetricType::L2);
  EXPECT_EQ(diskann->quantize_type(), QuantizeType::INT8);
  EXPECT_FALSE(diskann->quantizer_param().enable_rotate());
  EXPECT_EQ(diskann->max_degree(), 64);
  EXPECT_EQ(diskann->list_size(), 128);
  EXPECT_EQ(diskann->pq_chunk_num(), 16);

  size_t plain_index = 8;
  if (with_ivf_rabitq) {
    EXPECT_EQ(fields[8]->name(), "f_ivf_rabitq");
    EXPECT_EQ(fields[8]->data_type(), DataType::VECTOR_FP32);
    EXPECT_EQ(fields[8]->dimension(), 1024u);
    const auto ivf_rabitq = dynamic_cast<const IvfRabitqIndexParams *>(
        fields[8]->index_params().get());
    ASSERT_NE(ivf_rabitq, nullptr);
    EXPECT_EQ(ivf_rabitq->metric_type(), MetricType::L2);
    EXPECT_EQ(ivf_rabitq->quantize_type(), QuantizeType::RABITQ);
    EXPECT_EQ(ivf_rabitq->nlist(), 2048);
    EXPECT_EQ(ivf_rabitq->total_bits(), 6);
    EXPECT_EQ(ivf_rabitq->sample_count(), 200000);
    plain_index = 9;
  }

  EXPECT_EQ(fields[plain_index]->name(), "f_plain");
  EXPECT_EQ(fields[plain_index]->data_type(), DataType::ARRAY_DOUBLE);
  EXPECT_EQ(fields[plain_index]->dimension(), 0u);
  EXPECT_EQ(fields[plain_index]->index_params(), nullptr);
}

//! Checks the segment layout shared by kGoldenAllIndexTypes and
//! kGoldenAllNineIndexTypes.
void ExpectRichSegments(const ManifestData &data) {
  ASSERT_EQ(data.persisted_segment_metas.size(), 2u);
  for (uint32_t i = 0; i < 2; ++i) {
    const auto &segment = *data.persisted_segment_metas[i];
    EXPECT_EQ(segment.id(), i);
    ASSERT_EQ(segment.persisted_blocks().size(), 1u);
    const auto &block = segment.persisted_blocks()[0];
    EXPECT_EQ(block.id(), i);
    EXPECT_EQ(block.type(), BlockType::SCALAR);
    EXPECT_EQ(block.min_doc_id(), i * 1000u);
    EXPECT_EQ(block.max_doc_id(), i * 1000u + 999u);
    EXPECT_EQ(block.doc_count(), 1000u);
    ASSERT_EQ(block.columns().size(), 1u);
    EXPECT_EQ(block.columns()[0], "pk");
    EXPECT_FALSE(segment.has_writing_forward_block());
    ASSERT_EQ(segment.indexed_vector_fields().size(), 1u);
    EXPECT_EQ(segment.indexed_vector_fields().count("f_hnsw"), 1u);
  }

  ASSERT_NE(data.writing_segment_meta, nullptr);
  EXPECT_EQ(data.writing_segment_meta->id(), 2u);
  EXPECT_TRUE(data.writing_segment_meta->persisted_blocks().empty());
  EXPECT_TRUE(data.writing_segment_meta->indexed_vector_fields().empty());
  ASSERT_TRUE(data.writing_segment_meta->has_writing_forward_block());
  const auto &writing_block =
      data.writing_segment_meta->writing_forward_block();
  EXPECT_EQ(writing_block->id(), 0u);
  EXPECT_EQ(writing_block->type(), BlockType::SCALAR);
  EXPECT_EQ(writing_block->min_doc_id(), 0u);
  EXPECT_EQ(writing_block->max_doc_id(), 0u);
  EXPECT_EQ(writing_block->doc_count(), 0u);
  EXPECT_TRUE(writing_block->columns().empty());
}

}  // namespace

TEST(ManifestCodecGolden, DefaultSchemaManifest) {
  auto data = ExpectStableRoundTrip(Golden(kGoldenEmpty), "default_schema");
  ASSERT_NE(data.schema, nullptr);
  EXPECT_TRUE(data.schema->name().empty());
  EXPECT_TRUE(data.schema->fields().empty());
  EXPECT_EQ(data.schema->max_doc_count_per_segment(), 10000000u);
  EXPECT_EQ(data.version, 0u);
  EXPECT_FALSE(data.enable_mmap);
  EXPECT_TRUE(data.persisted_segment_metas.empty());
  EXPECT_EQ(data.writing_segment_meta, nullptr);
  EXPECT_EQ(data.id_map_path_suffix, 0u);
  EXPECT_EQ(data.delete_snapshot_path_suffix, 0u);
  EXPECT_EQ(data.next_segment_id, 0u);
}

TEST(ManifestCodecGolden, ZeroByteInput) {
  // A truly empty protobuf message is valid. The old reader produced all
  // defaults, including an empty schema with max_doc_count_per_segment zero.
  ManifestData data;
  ASSERT_TRUE(ManifestCodec::Decode("", &data).ok());
  ASSERT_NE(data.schema, nullptr);
  EXPECT_TRUE(data.schema->name().empty());
  EXPECT_TRUE(data.schema->fields().empty());
  EXPECT_EQ(data.schema->max_doc_count_per_segment(), 0u);
  EXPECT_EQ(data.version, 0u);
  EXPECT_FALSE(data.enable_mmap);
  EXPECT_TRUE(data.persisted_segment_metas.empty());
  EXPECT_EQ(data.writing_segment_meta, nullptr);
  EXPECT_EQ(data.id_map_path_suffix, 0u);
  EXPECT_EQ(data.delete_snapshot_path_suffix, 0u);
  EXPECT_EQ(data.next_segment_id, 0u);

  // Re-encoding matches the old load-then-save behaviour: the fallback
  // schema is written back as an empty-but-present schema message.
  std::string reencoded;
  ASSERT_TRUE(ManifestCodec::Encode(data, &reencoded).ok());
  EXPECT_EQ(reencoded, Golden(kGoldenEmptySchemaMsg));
}

TEST(ManifestCodecGolden, MissingSchemaMessage) {
  ManifestData data;
  ASSERT_TRUE(ManifestCodec::Decode(Golden(kGoldenNoSchema), &data).ok());
  ASSERT_NE(data.schema, nullptr);
  EXPECT_TRUE(data.schema->name().empty());
  EXPECT_TRUE(data.schema->fields().empty());
  EXPECT_EQ(data.schema->max_doc_count_per_segment(), 0u);
  EXPECT_EQ(data.version, 0u);
  EXPECT_TRUE(data.enable_mmap);
  EXPECT_TRUE(data.persisted_segment_metas.empty());
  EXPECT_EQ(data.writing_segment_meta, nullptr);
  EXPECT_EQ(data.id_map_path_suffix, 3u);
  EXPECT_EQ(data.delete_snapshot_path_suffix, 0u);
  EXPECT_EQ(data.next_segment_id, 7u);

  std::string reencoded;
  ASSERT_TRUE(ManifestCodec::Encode(data, &reencoded).ok());
  EXPECT_EQ(reencoded, Golden(kGoldenNoSchemaCanonical));

  // Decoding the canonical form is equivalent.
  ManifestData again;
  ASSERT_TRUE(ManifestCodec::Decode(reencoded, &again).ok());
  ASSERT_NE(again.schema, nullptr);
  EXPECT_TRUE(again.schema->name().empty());
  EXPECT_EQ(again.schema->max_doc_count_per_segment(), 0u);
  EXPECT_TRUE(again.enable_mmap);
  EXPECT_EQ(again.id_map_path_suffix, 3u);
  EXPECT_EQ(again.next_segment_id, 7u);
}

TEST(ManifestCodecGolden, EmptySchemaMessage) {
  auto data =
      ExpectStableRoundTrip(Golden(kGoldenEmptySchemaMsg), "empty_schema_msg");
  ASSERT_NE(data.schema, nullptr);
  EXPECT_TRUE(data.schema->name().empty());
  EXPECT_TRUE(data.schema->fields().empty());
  EXPECT_EQ(data.schema->max_doc_count_per_segment(), 0u);
  EXPECT_EQ(data.version, 0u);
  EXPECT_FALSE(data.enable_mmap);
  EXPECT_TRUE(data.persisted_segment_metas.empty());
  EXPECT_EQ(data.writing_segment_meta, nullptr);
  EXPECT_EQ(data.id_map_path_suffix, 0u);
  EXPECT_EQ(data.delete_snapshot_path_suffix, 0u);
  EXPECT_EQ(data.next_segment_id, 0u);
}

TEST(ManifestCodecGolden, SchemaWithoutMaxDocCount) {
  auto data = ExpectStableRoundTrip(Golden(kGoldenSchemaNoMaxDocCount),
                                    "schema_without_max_doc_count");
  ASSERT_NE(data.schema, nullptr);
  EXPECT_EQ(data.schema->name(), "nomax");
  EXPECT_TRUE(data.schema->fields().empty());
  EXPECT_EQ(data.schema->max_doc_count_per_segment(), 0u);
}

TEST(ManifestCodecGolden, SimpleManifest) {
  auto data = ExpectStableRoundTrip(Golden(kGoldenSimple), "simple");
  ASSERT_NE(data.schema, nullptr);
  EXPECT_EQ(data.schema->name(), "simple");
  EXPECT_EQ(data.schema->max_doc_count_per_segment(), 100000u);

  const auto fields = data.schema->fields();
  ASSERT_EQ(fields.size(), 2u);

  EXPECT_EQ(fields[0]->name(), "pk");
  EXPECT_EQ(fields[0]->data_type(), DataType::STRING);
  EXPECT_EQ(fields[0]->dimension(), 0u);
  EXPECT_FALSE(fields[0]->nullable());
  EXPECT_EQ(fields[0]->index_params(), nullptr);

  EXPECT_EQ(fields[1]->name(), "dense");
  EXPECT_EQ(fields[1]->data_type(), DataType::VECTOR_FP32);
  EXPECT_EQ(fields[1]->dimension(), 128u);
  EXPECT_FALSE(fields[1]->nullable());
  const auto dense_params = fields[1]->index_params();
  ASSERT_NE(dense_params, nullptr);
  ASSERT_EQ(dense_params->type(), IndexType::HNSW);
  auto *hnsw = dynamic_cast<const HnswIndexParams *>(dense_params.get());
  ASSERT_NE(hnsw, nullptr);
  EXPECT_EQ(hnsw->metric_type(), MetricType::IP);
  EXPECT_EQ(hnsw->m(), 16);
  EXPECT_EQ(hnsw->ef_construction(), 200);
  EXPECT_EQ(hnsw->quantize_type(), QuantizeType::UNDEFINED);
  EXPECT_FALSE(hnsw->use_contiguous_memory());
  // The quantizer_param sub-message is present but empty on the wire.
  EXPECT_FALSE(hnsw->quantizer_param().enable_rotate());

  EXPECT_EQ(data.version, 0u);
  EXPECT_TRUE(data.enable_mmap);
  EXPECT_EQ(data.id_map_path_suffix, 0u);
  EXPECT_EQ(data.delete_snapshot_path_suffix, 0u);
  EXPECT_EQ(data.next_segment_id, 1u);

  ASSERT_EQ(data.persisted_segment_metas.size(), 1u);
  const auto &segment = *data.persisted_segment_metas[0];
  EXPECT_EQ(segment.id(), 0u);
  ASSERT_EQ(segment.persisted_blocks().size(), 1u);
  const auto &block = segment.persisted_blocks()[0];
  EXPECT_EQ(block.id(), 0u);
  EXPECT_EQ(block.type(), BlockType::SCALAR);
  EXPECT_EQ(block.min_doc_id(), 0u);
  EXPECT_EQ(block.max_doc_id(), 0u);
  EXPECT_EQ(block.doc_count(), 10u);
  ASSERT_EQ(block.columns().size(), 1u);
  EXPECT_EQ(block.columns()[0], "pk");
  EXPECT_FALSE(segment.has_writing_forward_block());
  EXPECT_TRUE(segment.indexed_vector_fields().empty());

  EXPECT_EQ(data.writing_segment_meta, nullptr);
}

TEST(ManifestCodecGolden, AllIndexTypes) {
  auto data =
      ExpectStableRoundTrip(Golden(kGoldenAllIndexTypes), "all_index_types");
  ASSERT_NE(data.schema, nullptr);
  EXPECT_EQ(data.schema->name(), "rich");
  EXPECT_EQ(data.schema->max_doc_count_per_segment(), 1u << 20);
  ExpectRichSchemaFields(*data.schema, /*with_ivf_rabitq=*/false);

  EXPECT_EQ(data.version, 0u);
  EXPECT_TRUE(data.enable_mmap);
  ExpectRichSegments(data);
  EXPECT_EQ(data.id_map_path_suffix, 5u);
  EXPECT_EQ(data.delete_snapshot_path_suffix, 9u);
  EXPECT_EQ(data.next_segment_id, 12u);
}

TEST(ManifestCodecGolden, AllNineIndexTypes) {
  auto data = ExpectStableRoundTrip(Golden(kGoldenAllNineIndexTypes),
                                    "all_nine_index_types");
  ASSERT_NE(data.schema, nullptr);
  EXPECT_EQ(data.schema->name(), "rich9");
  EXPECT_EQ(data.schema->max_doc_count_per_segment(), 1u << 20);
  ExpectRichSchemaFields(*data.schema, /*with_ivf_rabitq=*/true);

  EXPECT_EQ(data.version, 0u);
  EXPECT_TRUE(data.enable_mmap);
  ExpectRichSegments(data);
  EXPECT_EQ(data.id_map_path_suffix, 5u);
  EXPECT_EQ(data.delete_snapshot_path_suffix, 9u);
  EXPECT_EQ(data.next_segment_id, 12u);
}

TEST(ManifestCodecGolden, AllDefaultIndexParams) {
  auto data = ExpectStableRoundTrip(Golden(kGoldenAllDefaultIndexParams),
                                    "all_default_index_params");
  ASSERT_NE(data.schema, nullptr);
  EXPECT_EQ(data.schema->name(), "defaults");
  EXPECT_TRUE(data.schema->fields().size() == 9u);
  EXPECT_EQ(data.schema->max_doc_count_per_segment(), 4096u);

  const auto fields = data.schema->fields();
  const std::vector<IndexType> expected = {
      IndexType::INVERT, IndexType::HNSW,        IndexType::FLAT,
      IndexType::IVF,    IndexType::HNSW_RABITQ, IndexType::VAMANA,
      IndexType::FTS,    IndexType::DISKANN,     IndexType::IVF_RABITQ};
  for (size_t i = 0; i < expected.size(); ++i) {
    const auto params = fields[i]->index_params();
    ASSERT_NE(params, nullptr) << "field " << fields[i]->name();
    EXPECT_EQ(params->type(), expected[i]) << "field " << fields[i]->name();
    EXPECT_FALSE(fields[i]->nullable()) << "field " << fields[i]->name();
  }

  EXPECT_EQ(fields[0]->name(), "d_invert");
  EXPECT_EQ(fields[0]->data_type(), DataType::INT64);
  const auto invert =
      dynamic_cast<const InvertIndexParams *>(fields[0]->index_params().get());
  ASSERT_NE(invert, nullptr);
  EXPECT_FALSE(invert->enable_range_optimization());

  const auto hnsw =
      dynamic_cast<const HnswIndexParams *>(fields[1]->index_params().get());
  ASSERT_NE(hnsw, nullptr);
  EXPECT_EQ(hnsw->metric_type(), MetricType::UNDEFINED);
  EXPECT_EQ(hnsw->quantize_type(), QuantizeType::UNDEFINED);
  EXPECT_EQ(hnsw->m(), 0);
  EXPECT_EQ(hnsw->ef_construction(), 0);
  EXPECT_FALSE(hnsw->use_contiguous_memory());
  EXPECT_FALSE(hnsw->quantizer_param().enable_rotate());

  const auto flat =
      dynamic_cast<const FlatIndexParams *>(fields[2]->index_params().get());
  ASSERT_NE(flat, nullptr);
  EXPECT_EQ(flat->metric_type(), MetricType::UNDEFINED);
  EXPECT_EQ(flat->quantize_type(), QuantizeType::UNDEFINED);
  EXPECT_FALSE(flat->quantizer_param().enable_rotate());

  const auto ivf =
      dynamic_cast<const IVFIndexParams *>(fields[3]->index_params().get());
  ASSERT_NE(ivf, nullptr);
  EXPECT_EQ(ivf->metric_type(), MetricType::UNDEFINED);
  EXPECT_EQ(ivf->quantize_type(), QuantizeType::UNDEFINED);
  EXPECT_EQ(ivf->n_list(), 0);
  EXPECT_EQ(ivf->n_iters(), 0);
  EXPECT_FALSE(ivf->use_soar());
  EXPECT_FALSE(ivf->quantizer_param().enable_rotate());

  // HNSW_RABITQ and IVF_RABITQ fix quantize_type to RABITQ at construction
  // time, so even their all-default encoding carries it inside base.
  const auto hnsw_rabitq = dynamic_cast<const HnswRabitqIndexParams *>(
      fields[4]->index_params().get());
  ASSERT_NE(hnsw_rabitq, nullptr);
  EXPECT_EQ(hnsw_rabitq->metric_type(), MetricType::UNDEFINED);
  EXPECT_EQ(hnsw_rabitq->quantize_type(), QuantizeType::RABITQ);
  EXPECT_EQ(hnsw_rabitq->m(), 0);
  EXPECT_EQ(hnsw_rabitq->ef_construction(), 0);
  EXPECT_EQ(hnsw_rabitq->total_bits(), 0);
  EXPECT_EQ(hnsw_rabitq->num_clusters(), 0);
  EXPECT_EQ(hnsw_rabitq->sample_count(), 0);

  const auto vamana =
      dynamic_cast<const VamanaIndexParams *>(fields[5]->index_params().get());
  ASSERT_NE(vamana, nullptr);
  EXPECT_EQ(vamana->metric_type(), MetricType::UNDEFINED);
  EXPECT_EQ(vamana->quantize_type(), QuantizeType::UNDEFINED);
  EXPECT_EQ(vamana->max_degree(), 0);
  EXPECT_EQ(vamana->search_list_size(), 0);
  EXPECT_FLOAT_EQ(vamana->alpha(), 0.0f);
  EXPECT_FALSE(vamana->saturate_graph());
  EXPECT_FALSE(vamana->use_contiguous_memory());
  EXPECT_FALSE(vamana->use_id_map());
  EXPECT_FALSE(vamana->quantizer_param().enable_rotate());

  const auto fts =
      dynamic_cast<const FtsIndexParams *>(fields[6]->index_params().get());
  ASSERT_NE(fts, nullptr);
  EXPECT_TRUE(fts->tokenizer_name().empty());
  EXPECT_TRUE(fts->filters().empty());
  EXPECT_TRUE(fts->extra_params().empty());

  const auto diskann =
      dynamic_cast<const DiskAnnIndexParams *>(fields[7]->index_params().get());
  ASSERT_NE(diskann, nullptr);
  EXPECT_EQ(diskann->metric_type(), MetricType::UNDEFINED);
  EXPECT_EQ(diskann->quantize_type(), QuantizeType::UNDEFINED);
  EXPECT_EQ(diskann->max_degree(), 0);
  EXPECT_EQ(diskann->list_size(), 0);
  EXPECT_EQ(diskann->pq_chunk_num(), 0);
  EXPECT_FALSE(diskann->quantizer_param().enable_rotate());

  const auto ivf_rabitq = dynamic_cast<const IvfRabitqIndexParams *>(
      fields[8]->index_params().get());
  ASSERT_NE(ivf_rabitq, nullptr);
  EXPECT_EQ(ivf_rabitq->metric_type(), MetricType::UNDEFINED);
  EXPECT_EQ(ivf_rabitq->quantize_type(), QuantizeType::RABITQ);
  EXPECT_EQ(ivf_rabitq->nlist(), 0);
  EXPECT_EQ(ivf_rabitq->total_bits(), 0);
  EXPECT_EQ(ivf_rabitq->sample_count(), 0);
}

TEST(ManifestCodecGolden, MultiBlockManifest) {
  auto data = ExpectStableRoundTrip(Golden(kGoldenMultiBlock), "multi_block");
  ASSERT_NE(data.schema, nullptr);
  EXPECT_EQ(data.schema->name(), "multi");
  EXPECT_EQ(data.schema->max_doc_count_per_segment(), 5000u);

  const auto fields = data.schema->fields();
  ASSERT_EQ(fields.size(), 3u);
  EXPECT_EQ(fields[0]->name(), "pk");
  EXPECT_EQ(fields[0]->data_type(), DataType::STRING);
  EXPECT_FALSE(fields[0]->nullable());
  EXPECT_EQ(fields[0]->index_params(), nullptr);
  EXPECT_EQ(fields[1]->name(), "dense");
  EXPECT_EQ(fields[1]->data_type(), DataType::VECTOR_FP32);
  EXPECT_EQ(fields[1]->dimension(), 4u);
  EXPECT_FALSE(fields[1]->nullable());
  EXPECT_EQ(fields[2]->name(), "title");
  EXPECT_EQ(fields[2]->data_type(), DataType::STRING);
  EXPECT_TRUE(fields[2]->nullable());
  const auto title_fts =
      dynamic_cast<const FtsIndexParams *>(fields[2]->index_params().get());
  ASSERT_NE(title_fts, nullptr);
  EXPECT_EQ(title_fts->tokenizer_name(), "standard");
  ASSERT_EQ(title_fts->filters().size(), 1u);
  EXPECT_EQ(title_fts->filters()[0], "lowercase");
  EXPECT_TRUE(title_fts->extra_params().empty());

  ASSERT_EQ(data.persisted_segment_metas.size(), 2u);

  const auto &segment3 = *data.persisted_segment_metas[0];
  EXPECT_EQ(segment3.id(), 3u);
  ASSERT_EQ(segment3.persisted_blocks().size(), 5u);

  const auto &block0 = segment3.persisted_blocks()[0];
  EXPECT_EQ(block0.id(), 0u);
  EXPECT_EQ(block0.type(), BlockType::SCALAR);
  EXPECT_EQ(block0.min_doc_id(), 0u);
  EXPECT_EQ(block0.max_doc_id(), 999u);
  EXPECT_EQ(block0.doc_count(), 1000u);
  ASSERT_EQ(block0.columns().size(), 1u);
  EXPECT_EQ(block0.columns()[0], "pk");

  const auto &block1 = segment3.persisted_blocks()[1];
  EXPECT_EQ(block1.id(), 1u);
  EXPECT_EQ(block1.type(), BlockType::VECTOR_INDEX);
  EXPECT_EQ(block1.min_doc_id(), 0u);
  EXPECT_EQ(block1.max_doc_id(), 999u);
  EXPECT_EQ(block1.doc_count(), 1000u);
  ASSERT_EQ(block1.columns().size(), 1u);
  EXPECT_EQ(block1.columns()[0], "dense");

  const auto &block2 = segment3.persisted_blocks()[2];
  EXPECT_EQ(block2.id(), 2u);
  EXPECT_EQ(block2.type(), BlockType::VECTOR_INDEX_QUANTIZE);
  EXPECT_EQ(block2.min_doc_id(), 1000u);
  EXPECT_EQ(block2.max_doc_id(), 1999u);
  EXPECT_EQ(block2.doc_count(), 1000u);
  ASSERT_EQ(block2.columns().size(), 1u);
  EXPECT_EQ(block2.columns()[0], "dense");

  const auto &block3 = segment3.persisted_blocks()[3];
  EXPECT_EQ(block3.id(), 3u);
  EXPECT_EQ(block3.type(), BlockType::SCALAR_INDEX);
  EXPECT_EQ(block3.min_doc_id(), 0u);
  EXPECT_EQ(block3.max_doc_id(), 1999u);
  EXPECT_EQ(block3.doc_count(), 2000u);
  ASSERT_EQ(block3.columns().size(), 2u);
  EXPECT_EQ(block3.columns()[0], "pk");
  EXPECT_EQ(block3.columns()[1], "title");

  const auto &block4 = segment3.persisted_blocks()[4];
  EXPECT_EQ(block4.id(), 4u);
  EXPECT_EQ(block4.type(), BlockType::FTS_INDEX);
  EXPECT_EQ(block4.min_doc_id(), 0u);
  EXPECT_EQ(block4.max_doc_id(), 1999u);
  EXPECT_EQ(block4.doc_count(), 2000u);
  ASSERT_EQ(block4.columns().size(), 1u);
  EXPECT_EQ(block4.columns()[0], "title");

  ASSERT_TRUE(segment3.has_writing_forward_block());
  const auto &writing_block = segment3.writing_forward_block();
  EXPECT_EQ(writing_block->id(), 9u);
  EXPECT_EQ(writing_block->type(), BlockType::SCALAR);
  EXPECT_EQ(writing_block->min_doc_id(), 2000u);
  EXPECT_EQ(writing_block->max_doc_id(), 2004u);
  EXPECT_EQ(writing_block->doc_count(), 5u);
  EXPECT_TRUE(writing_block->columns().empty());

  ASSERT_EQ(segment3.indexed_vector_fields().size(), 2u);
  EXPECT_EQ(segment3.indexed_vector_fields().count("dense"), 1u);
  EXPECT_EQ(segment3.indexed_vector_fields().count("title"), 1u);

  // A segment may carry nothing but its ID.
  const auto &segment4 = *data.persisted_segment_metas[1];
  EXPECT_EQ(segment4.id(), 4u);
  EXPECT_TRUE(segment4.persisted_blocks().empty());
  EXPECT_FALSE(segment4.has_writing_forward_block());
  EXPECT_TRUE(segment4.indexed_vector_fields().empty());

  ASSERT_NE(data.writing_segment_meta, nullptr);
  EXPECT_EQ(data.writing_segment_meta->id(), 5u);
  EXPECT_TRUE(data.writing_segment_meta->persisted_blocks().empty());
  ASSERT_TRUE(data.writing_segment_meta->has_writing_forward_block());
  EXPECT_EQ(data.writing_segment_meta->writing_forward_block()->type(),
            BlockType::SCALAR);

  EXPECT_EQ(data.version, 0u);
  EXPECT_FALSE(data.enable_mmap);
  EXPECT_EQ(data.id_map_path_suffix, 0u);
  EXPECT_EQ(data.delete_snapshot_path_suffix, 0u);
  EXPECT_EQ(data.next_segment_id, 6u);
}

TEST(ManifestCodecGolden, BoundaryValues) {
  constexpr auto kUint32Max = std::numeric_limits<uint32_t>::max();
  constexpr auto kUint64Max = std::numeric_limits<uint64_t>::max();
  constexpr auto kInt32Max = std::numeric_limits<int32_t>::max();

  auto data = ExpectStableRoundTrip(Golden(kGoldenBoundary), "boundary");
  EXPECT_EQ(data.version, 1u);

  ASSERT_NE(data.schema, nullptr);
  EXPECT_EQ(data.schema->name(), "boundary");
  EXPECT_EQ(data.schema->max_doc_count_per_segment(), kUint64Max);

  const auto fields = data.schema->fields();
  ASSERT_EQ(fields.size(), 3u);

  EXPECT_EQ(fields[0]->name(), "vec");
  EXPECT_EQ(fields[0]->dimension(), kUint32Max);
  EXPECT_TRUE(fields[0]->nullable());
  const auto hnsw =
      dynamic_cast<const HnswIndexParams *>(fields[0]->index_params().get());
  ASSERT_NE(hnsw, nullptr);
  EXPECT_EQ(hnsw->metric_type(), MetricType::COSINE);
  EXPECT_EQ(hnsw->quantize_type(), QuantizeType::INT8);
  EXPECT_TRUE(hnsw->quantizer_param().enable_rotate());
  EXPECT_EQ(hnsw->m(), kInt32Max);
  EXPECT_EQ(hnsw->ef_construction(), kInt32Max);
  EXPECT_TRUE(hnsw->use_contiguous_memory());

  EXPECT_EQ(fields[1]->name(), "vam");
  EXPECT_EQ(fields[1]->dimension(), 8u);
  EXPECT_FALSE(fields[1]->nullable());
  const auto vamana =
      dynamic_cast<const VamanaIndexParams *>(fields[1]->index_params().get());
  ASSERT_NE(vamana, nullptr);
  EXPECT_EQ(vamana->metric_type(), MetricType::IP);
  EXPECT_EQ(vamana->quantize_type(), QuantizeType::UNDEFINED);
  EXPECT_FALSE(vamana->quantizer_param().enable_rotate());
  EXPECT_EQ(vamana->max_degree(), kInt32Max);
  EXPECT_EQ(vamana->search_list_size(), kInt32Max);
  EXPECT_FLOAT_EQ(vamana->alpha(), -2.5f);
  EXPECT_FALSE(vamana->saturate_graph());
  EXPECT_FALSE(vamana->use_contiguous_memory());
  EXPECT_FALSE(vamana->use_id_map());

  // Repeated strings stay written even when empty.
  EXPECT_EQ(fields[2]->name(), "fts2");
  const auto fts =
      dynamic_cast<const FtsIndexParams *>(fields[2]->index_params().get());
  ASSERT_NE(fts, nullptr);
  EXPECT_TRUE(fts->tokenizer_name().empty());
  ASSERT_EQ(fts->filters().size(), 2u);
  EXPECT_TRUE(fts->filters()[0].empty());
  EXPECT_TRUE(fts->filters()[1].empty());
  EXPECT_TRUE(fts->extra_params().empty());

  ASSERT_EQ(data.persisted_segment_metas.size(), 1u);
  const auto &segment = *data.persisted_segment_metas[0];
  EXPECT_EQ(segment.id(), 7u);
  ASSERT_EQ(segment.persisted_blocks().size(), 1u);
  const auto &block = segment.persisted_blocks()[0];
  EXPECT_EQ(block.id(), kUint32Max);
  EXPECT_EQ(block.type(), BlockType::VECTOR_INDEX);
  EXPECT_EQ(block.min_doc_id(), kUint64Max - 1);
  EXPECT_EQ(block.max_doc_id(), kUint64Max);
  EXPECT_EQ(block.doc_count(), kUint32Max);
  ASSERT_EQ(block.columns().size(), 1u);
  EXPECT_EQ(block.columns()[0], "x");
  ASSERT_EQ(segment.indexed_vector_fields().size(), 1u);
  EXPECT_EQ(segment.indexed_vector_fields().count("vec"), 1u);

  EXPECT_TRUE(data.enable_mmap);
  EXPECT_EQ(data.id_map_path_suffix, kUint32Max);
  EXPECT_EQ(data.delete_snapshot_path_suffix, kUint32Max);
  EXPECT_EQ(data.next_segment_id, kUint32Max);
}

TEST(ManifestCodecGolden, EmptyIndexParamsMessage) {
  const auto field =
      ManifestCodec::DecodeFieldSchema(Golden(kGoldenEmptyIndexParamsMsg));
  ASSERT_NE(field, nullptr);
  EXPECT_EQ(field->name(), "x");
  EXPECT_EQ(field->data_type(), DataType::STRING);
  EXPECT_EQ(field->dimension(), 0u);
  EXPECT_FALSE(field->nullable());
  // A present IndexParams message without any oneof branch decodes to null,
  // exactly as the old protobuf-based converter did.
  EXPECT_EQ(field->index_params(), nullptr);
  EXPECT_EQ(ManifestCodec::DecodeIndexParams(""), nullptr);

  // Re-encoding drops the empty message.
  std::string reencoded;
  ManifestCodec::EncodeFieldSchema(*field, &reencoded);
  EXPECT_EQ(reencoded, Golden(kGoldenEmptyIndexParamsMsg).substr(0, 5));
}

TEST(ManifestCodecGolden, IvfRabitqIndexParams) {
  const std::string golden = Golden(kGoldenIvfRabitq);

  // Encoding must produce exactly the bytes an older reader expects. Note the
  // base sub-message carries no quantizer_param, matching HNSW_RABITQ.
  IvfRabitqIndexParams params(MetricType::L2, 1024, 5, 100000);
  std::string encoded;
  ManifestCodec::EncodeIndexParams(&params, &encoded);
  EXPECT_EQ(encoded, golden)
      << "the on-disk encoding of IVF_RABITQ index params must stay stable";

  // ... and decoding the golden bytes must round trip every field.
  const auto decoded = ManifestCodec::DecodeIndexParams(golden);
  ASSERT_NE(decoded, nullptr);
  ASSERT_EQ(decoded->type(), IndexType::IVF_RABITQ);
  auto *ivf_rabitq = dynamic_cast<const IvfRabitqIndexParams *>(decoded.get());
  ASSERT_NE(ivf_rabitq, nullptr);
  EXPECT_EQ(ivf_rabitq->metric_type(), MetricType::L2);
  EXPECT_EQ(ivf_rabitq->quantize_type(), QuantizeType::RABITQ);
  EXPECT_EQ(ivf_rabitq->nlist(), 1024);
  EXPECT_EQ(ivf_rabitq->total_bits(), 5);
  EXPECT_EQ(ivf_rabitq->sample_count(), 100000);
  EXPECT_EQ(*decoded, params);
}

TEST(ManifestCodecGolden, VamanaTwoPassBuild) {
  // two_pass_build (proto field 8) was added after the golden bytes were
  // archived, so it has no legacy byte fixture: manifests written before it
  // existed must decode to the default (false), and the flag must round trip.
  VamanaIndexParams disabled(MetricType::L2, 48, 160, 1.4f);
  VamanaIndexParams enabled(MetricType::L2, 48, 160, 1.4f, false, false, false,
                            QuantizeType::UNDEFINED, QuantizerParam(), true);

  std::string encoded_disabled;
  ManifestCodec::EncodeIndexParams(&disabled, &encoded_disabled);
  std::string encoded_enabled;
  ManifestCodec::EncodeIndexParams(&enabled, &encoded_enabled);
  // A default-valued bool is not serialized, so only one encoding carries it.
  EXPECT_NE(encoded_disabled, encoded_enabled);

  const auto decoded_disabled =
      ManifestCodec::DecodeIndexParams(encoded_disabled);
  ASSERT_NE(decoded_disabled, nullptr);
  ASSERT_EQ(decoded_disabled->type(), IndexType::VAMANA);
  EXPECT_FALSE(dynamic_cast<const VamanaIndexParams *>(decoded_disabled.get())
                   ->two_pass_build());
  EXPECT_EQ(*decoded_disabled, disabled);

  const auto decoded_enabled =
      ManifestCodec::DecodeIndexParams(encoded_enabled);
  ASSERT_NE(decoded_enabled, nullptr);
  ASSERT_EQ(decoded_enabled->type(), IndexType::VAMANA);
  const auto *vamana =
      dynamic_cast<const VamanaIndexParams *>(decoded_enabled.get());
  ASSERT_NE(vamana, nullptr);
  EXPECT_TRUE(vamana->two_pass_build());
  EXPECT_EQ(*decoded_enabled, enabled);
}

TEST(ManifestCodecGolden, RefineFlatStorageParams) {
  HnswIndexParams hnsw(MetricType::L2, 16, 100, QuantizeType::INT8, true,
                       QuantizerParam(true), true, DataType::VECTOR_UINT8);
  std::string encoded_hnsw;
  ManifestCodec::EncodeIndexParams(&hnsw, &encoded_hnsw);
  const auto decoded_hnsw = ManifestCodec::DecodeIndexParams(encoded_hnsw);
  ASSERT_NE(decoded_hnsw, nullptr);
  const auto *hnsw_params =
      dynamic_cast<const HnswIndexParams *>(decoded_hnsw.get());
  ASSERT_NE(hnsw_params, nullptr);
  EXPECT_TRUE(hnsw_params->use_flat_contiguous_memory());
  EXPECT_EQ(hnsw_params->flat_data_type(), DataType::VECTOR_UINT8);
  EXPECT_EQ(*decoded_hnsw, hnsw);

  FlatIndexParams flat(MetricType::L2, QuantizeType::UNDEFINED,
                       QuantizerParam(), true, DataType::VECTOR_UINT8);
  std::string encoded_flat;
  ManifestCodec::EncodeIndexParams(&flat, &encoded_flat);
  const auto decoded_flat = ManifestCodec::DecodeIndexParams(encoded_flat);
  ASSERT_NE(decoded_flat, nullptr);
  const auto *flat_params =
      dynamic_cast<const FlatIndexParams *>(decoded_flat.get());
  ASSERT_NE(flat_params, nullptr);
  EXPECT_TRUE(flat_params->use_contiguous_memory());
  EXPECT_EQ(flat_params->storage_data_type(), DataType::VECTOR_UINT8);
  EXPECT_EQ(*decoded_flat, flat);

  VamanaIndexParams vamana(MetricType::COSINE, 48, 96, 1.2f, true, true, true,
                           QuantizeType::FP16, QuantizerParam(true), true, true,
                           DataType::VECTOR_FP16);
  std::string encoded_vamana;
  ManifestCodec::EncodeIndexParams(&vamana, &encoded_vamana);
  const auto decoded_vamana = ManifestCodec::DecodeIndexParams(encoded_vamana);
  ASSERT_NE(decoded_vamana, nullptr);
  const auto *vamana_params =
      dynamic_cast<const VamanaIndexParams *>(decoded_vamana.get());
  ASSERT_NE(vamana_params, nullptr);
  EXPECT_TRUE(vamana_params->use_flat_contiguous_memory());
  EXPECT_EQ(vamana_params->flat_data_type(), DataType::VECTOR_FP16);
  EXPECT_EQ(*decoded_vamana, vamana);
}

TEST(ManifestCodecGolden, IndexParamsLastBranchWins) {
  // protobuf oneof semantics: when several branches appear on the wire the
  // last one wins.
  FlatIndexParams flat(MetricType::IP, QuantizeType::UNDEFINED,
                       QuantizerParam());
  HnswIndexParams hnsw(MetricType::L2, 16, 100, QuantizeType::UNDEFINED, false,
                       QuantizerParam());
  std::string flat_bytes;
  ManifestCodec::EncodeIndexParams(&flat, &flat_bytes);
  std::string hnsw_bytes;
  ManifestCodec::EncodeIndexParams(&hnsw, &hnsw_bytes);

  const auto decoded =
      ManifestCodec::DecodeIndexParams(flat_bytes + hnsw_bytes);
  ASSERT_NE(decoded, nullptr);
  EXPECT_EQ(decoded->type(), IndexType::HNSW);
}

TEST(ManifestCodecGolden, LegacyFieldNamesSurviveWithoutRevalidation) {
  // Older alter_column paths could persist names outside the schema rules.
  // Build the wire data without schema helpers so this also catches a decoder
  // silently dropping fields after a new validation check is added.
  const std::vector<std::string> names{"user name", std::string(65, 'f'),
                                       u8"历史字段", "_zvec_uid_"};
  std::string encoded_schema;
  pbwire::Writer schema_writer(&encoded_schema);
  schema_writer.PutString(1, "legacy_collection");
  for (const auto &name : names) {
    std::string encoded_field;
    pbwire::Writer field_writer(&encoded_field);
    field_writer.PutString(1, name);
    field_writer.PutVarint(2, 2);  // Persisted STRING data type.
    schema_writer.PutMessage(2, encoded_field);
  }
  schema_writer.PutVarint(3, 10000);
  std::string encoded_manifest;
  pbwire::Writer(&encoded_manifest).PutMessage(2, encoded_schema);

  ManifestData restored;
  auto status = ManifestCodec::Decode(encoded_manifest, &restored);
  ASSERT_TRUE(status.ok()) << status.message();
  ASSERT_NE(restored.schema, nullptr);
  ASSERT_EQ(restored.schema->fields().size(), names.size());
  for (size_t i = 0; i < names.size(); ++i) {
    SCOPED_TRACE(i);
    const auto *field = restored.schema->get_field(names[i]);
    ASSERT_NE(field, nullptr);
    EXPECT_EQ(field->name(), names[i]);
    EXPECT_EQ(field->data_type(), DataType::STRING);
    EXPECT_EQ(restored.schema->fields()[i]->name(), names[i]);
  }
  EXPECT_EQ(restored.schema->validate().code(), StatusCode::INVALID_ARGUMENT);

  std::string reencoded;
  status = ManifestCodec::Encode(restored, &reencoded);
  ASSERT_TRUE(status.ok()) << status.message();
  EXPECT_EQ(reencoded, encoded_manifest);
}

TEST(ManifestCodecGolden, DuplicateFieldsFailInsteadOfBeingSilentlyDropped) {
  // This malformed schema could previously be created through the C++ list
  // constructor. Restoring only its first field silently changes its meaning.
  CollectionSchema schema(
      "legacy", {std::make_shared<FieldSchema>("duplicate", DataType::INT32),
                 std::make_shared<FieldSchema>("duplicate", DataType::INT64)});
  std::string schema_bytes;
  ManifestCodec::EncodeCollectionSchema(schema, &schema_bytes);
  auto decoded_schema = ManifestCodec::DecodeCollectionSchema(schema_bytes);
  ASSERT_FALSE(decoded_schema.has_value());
  EXPECT_EQ(decoded_schema.error().code(), StatusCode::INTERNAL_ERROR);
  EXPECT_NE(decoded_schema.error().message().find("duplicate"),
            std::string::npos);

  std::string manifest_bytes;
  pbwire::Writer(&manifest_bytes).PutMessage(2, schema_bytes);
  ManifestData restored;
  auto status = ManifestCodec::Decode(manifest_bytes, &restored);
  EXPECT_EQ(status.code(), StatusCode::INTERNAL_ERROR);
  EXPECT_EQ(restored.schema, nullptr);
}

TEST(ManifestCodecGolden, MalformedNestedSchemaFailsExplicitly) {
  const std::string malformed_schema("\x0a\x05x", 3);
  std::string manifest_bytes;
  pbwire::Writer(&manifest_bytes).PutMessage(2, malformed_schema);
  ManifestData restored;
  auto status = ManifestCodec::Decode(manifest_bytes, &restored);
  EXPECT_EQ(status.code(), StatusCode::INTERNAL_ERROR);
  EXPECT_EQ(restored.schema, nullptr);
}

TEST(ManifestCodecGolden, StructuralSchemaHelpersPreserveLegacyNames) {
  CollectionSchema schema("legacy_collection");
  auto status = schema.add_field(
      std::make_shared<FieldSchema>("user name", DataType::STRING));
  ASSERT_TRUE(status.ok()) << status.message();
  status = schema.alter_field("user name", std::make_shared<FieldSchema>(
                                               u8"历史字段", DataType::STRING));
  ASSERT_TRUE(status.ok()) << status.message();
  EXPECT_FALSE(schema.has_field("user name"));
  ASSERT_TRUE(schema.has_field(u8"历史字段"));

  // Structural mutation is also used during recovery. Explicit validation is
  // kept separate, and legacy names can still be replaced with legal names.
  EXPECT_EQ(schema.validate().code(), StatusCode::INVALID_ARGUMENT);
  status = schema.alter_field(
      u8"历史字段", std::make_shared<FieldSchema>("renamed", DataType::STRING));
  ASSERT_TRUE(status.ok()) << status.message();
  EXPECT_TRUE(schema.validate().ok());
  EXPECT_TRUE(schema.has_field("renamed"));
}

TEST(ManifestCodecGolden, UnknownFieldsAreIgnored) {
  // Forward compatibility: a manifest written by a newer zvec may carry fields
  // this build does not know about. They must be skipped silently.
  std::string with_unknown = Golden(kGoldenSimple);
  {
    pbwire::Writer w(&with_unknown);
    w.PutVarint(99, 12345);               // unknown varint field
    w.PutMessage(100, std::string("x"));  // unknown length-delimited field
    w.PutFloat(101, 2.5f);                // unknown fixed32 field
  }

  ManifestData data;
  ASSERT_TRUE(ManifestCodec::Decode(with_unknown, &data).ok());
  ASSERT_NE(data.schema, nullptr);
  EXPECT_EQ(data.schema->name(), "simple");
  EXPECT_EQ(data.schema->fields().size(), 2u);
  EXPECT_EQ(data.next_segment_id, 1u);
}

TEST(ManifestCodecGolden, TruncatedInputDoesNotCrash) {
  const std::string golden = Golden(kGoldenAllIndexTypes);
  // Truncation at every offset must either be reported as an error or produce
  // a partial but well-formed result; it must never crash or hang.
  for (size_t len = 1; len < golden.size(); ++len) {
    ManifestData data;
    ManifestCodec::Decode(std::string_view(golden.data(), len), &data);
  }
}

TEST(ManifestCodecGolden, CorruptInputIsRejected) {
  // A length-delimited field claiming more bytes than are available.
  std::string bad_len;
  {
    pbwire::Writer w(&bad_len);
    w.PutMessage(2, std::string("payload"));
  }
  bad_len[1] = static_cast<char>(0x7F);  // overlong length
  ManifestData data;
  EXPECT_FALSE(ManifestCodec::Decode(bad_len, &data).ok());

  // A varint that never terminates.
  const std::string bad_varint(12, static_cast<char>(0xFF));
  ManifestData data2;
  EXPECT_FALSE(ManifestCodec::Decode(bad_varint, &data2).ok());

  // Field number zero is illegal.
  const std::string zero_field(1, static_cast<char>(0x00));
  ManifestData data3;
  EXPECT_FALSE(ManifestCodec::Decode(zero_field, &data3).ok());
}

TEST(ManifestCodecGolden, WireReaderRejectsGroups) {
  // Wire types 3 and 4 (deprecated groups) are never produced by the manifest
  // and must be treated as corrupt input rather than silently skipped.
  for (uint8_t type : {3, 4}) {
    std::string buf;
    buf.push_back(static_cast<char>((1 << 3) | type));
    pbwire::Reader r(buf);
    EXPECT_FALSE(r.Next());
    EXPECT_FALSE(r.ok());
  }
}
